# Generated by Django 2.1.7 on 2020-09-21 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.CharField(blank=True, max_length=140, null=True)),
                ('price', models.FloatField()),
                ('stock_amount', models.IntegerField()),
                ('package_details', models.CharField(max_length=20)),
                ('picture', models.ImageField(upload_to='images/product')),
                ('delivery_option', models.BooleanField(default=False)),
                ('category', models.CharField(choices=[('GROC', 'GROCERIES'), ('ELEC', 'ELECTRONICS'), ('CLTH', 'CLOTHES'), ('HOME', 'HOME AND LIVING')], max_length=5)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
